# Generated by Django 6.0.4 on 2026-05-05 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensaje',
            options={},
        ),
        migrations.AlterModelOptions(
            name='salachat',
            options={},
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salachat',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='salachat',
            name='participantes',
            field=models.ManyToManyField(related_name='salas_chat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salachat',
            name='tipo',
            field=models.CharField(choices=[('privado', 'Privado'), ('grupo', 'Grupo')], default='privado', max_length=10),
        ),
    ]
